### ISSUE TITLE
Frame drop/stutter every time combat is initiated and stopped

### ISSUE THREAD

**Issue by durrburger93** [PhenomDevel/BlizzHUDTweaks#55] opened 2023-07-28 14:24 UTC
Whenever I'm using the addon with combat modifiers, there is a noticeable frame drop or a stutter that's very visible on the frame time graph as well. 

I'm using the addon right now to hide many parts of the UI because I'm playing the game on an OLED screen so trying to keep the UI to a minimum, so I'm not sure which UI element precisely is causing the problem, but it IS less noticeable when I'm not hiding the action bars in/out of combat.

Reproduce
Just entering and leaving combat is enough to trigger the stutter, it happens every time.
The severity seems reduced when action bars aren't being managed.

Expected Behaviour
For there to be no performance impact from this if possible. 

Another potentially relevant factor is that I'm always seeing the "Interface actions failed because of this addon" error when mousing over this addon in the addon menu, so I'm not sure what interface actions it's preventing and if this is contributing to the stuttering.

**Comment by PhenomDevel** [comment] 2023-07-28 15:45
I have released a new version 1.33.7 which randomly delays the fades between 1 and 10ms. I am not sure what is causing the stuttering and not sure if this will actually help. 

I think it is the sheer amount of fades happening at the same time that is causing the stuttering. I can't reproduce it though without any addon except BHT.

**Comment by durrburger93** [comment] 2023-07-28 20:07
Is that build up because the latest one I'm seeing is still 1.33.6? Also were you able to reproduce the stuttering when using it for action bars specifically? That's when it's the most apparent on my end with big frame time spikes, but I'll gladly provide any logs you want if it would be of any help.

**Comment by PhenomDevel** [comment] 2023-07-28 20:26
Sorry, there was a problem with the build. 1.33.9 should be a new version in a few minutes.

I am checking it with no other addons active. The frametime jumps from 7.5 - 8.0 to about 8.5 - 9.0, which shouldn't cause much stuttering.

Let me know if the new version helps at all. If not, I'll have to look into it some more when I have time.

**Comment by durrburger93** [comment] 2023-07-29 14:38
Hey this build seems to have massively reduced this stutter actually, thanks a lot!

Just on a side note, I'm not seeing the option to fade or modify the chat window anymore. Was it ever included in the addon or am I tripping?

**Comment by PhenomDevel** [comment] 2023-07-29 20:10
I'll close this issue for now.

Chat is not included. It was in a very early version over a year ago. But since the chat has a lot of subframes, it is not that simple and there are specialized addons just for that.

**Closed by PhenomDevel** 2023-07-29 20:10 UTC
Labels: bug
