### ISSUE TITLE
[BUG] MicroMenu

### ISSUE THREAD

**Issue by RathianD** [PhenomDevel/BlizzHUDTweaks#54] opened 2023-07-13 09:38 UTC
## Description
> Please describe what the problem is as precise as possible
If you enable Mouseover Fading on the Micro Menu and you hover over the icons sometimes icons glitch out and disappear for short time.
    
## Reproduce
> What steps are needed to reproduce it?
1. Enable MicroMenu Fading in the options
2. Take your mouse curser and start clicking and/or hover over the micro menu bar from left to right 
3. Now you should see single icons glitch out and disappear for a short time or when you hover over the glitched out icon

## Expected Behaviour
> What did you expect what should have happend?
Just nothing

## Optional Context (e.g. Screenshots)
![Screenshot 2023-07-13 113414](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/070570c3-04c6-46ef-85ab-da4321af0a6e)

**Comment by PhenomDevel** [comment] 2023-07-13 09:49
I can't reproduce this behaviour with just BHT active.

I have a new character which has the micromenubar like this:
![image](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/13941819/24dc8301-61a0-493f-b070-6b1b8db3e04d)

This also glitches out in the sense of clicking an grayed out icon will change its display
![image](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/13941819/186c75d2-fe2f-47ef-b2e6-fc66d870bdbe)

Do you have any other addons active which can interfere with BHT

**Comment by RathianD** [comment] 2023-07-13 14:15
No i also tested it with all addons disabled still happens maybe i can send you a video

https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/8abc908e-1f19-4b6f-ac34-22cbe9c559d6

I hope this helps

**Comment by PhenomDevel** [comment] 2023-07-14 08:11
Ok i see... Still can't reproduce it with the defaults settings.

Could you take a screenshot of the settings for the micromenu?

If it uses the global fade a screenshot of those settings would help aswell.

**Comment by RathianD** [comment] 2023-07-14 10:24
Sure no problem 
![grafik](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/2b5dace9-2730-4b33-8d12-c667e23188c0)
![grafik](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/eccffbb7-0dbf-47ee-b80b-eaff567fd857)
![grafik](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/5a97651a-399e-4c92-b66f-85ccb0c31b28)
![grafik](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/b4d2bcd4-ae8d-4515-ac33-e3daef54356e)
![grafik](https://github.com/PhenomDevel/BlizzHUDTweaks/assets/139451298/ff85877f-b380-49e7-816f-3feffd7c6247)

If you need more just let me know ;)

**Comment by PhenomDevel** [comment] 2023-07-14 12:26
I was able to reproduce the behavior. Unfortunately, I have no real idea where it comes from. I think the weird behavior is the fading of the parent frame and how the children react to it when restarting animations (which sometimes happens when you enter or leave with the mouse at the perfect moment). Changing the refresh interval makes this much less likely. But there is nothing I can do about that right now.

**Comment by RathianD** [comment] 2023-07-14 12:29
Yeah no problem i mean it's not unusable i just noticed it and thought maybe it is woth to look into it. 
Thank you for the quick response !

**Comment by PhenomDevel** [comment] 2023-07-14 12:31
Sorry, I can't fix it right now and thanks for the report. 

I think it is fixable, but it would mean some digging down a rabbit hole that I don't want to invest the time in.

Keep reporting ;D 

I'll close this issue for now.

**Closed by PhenomDevel** 2023-07-14 12:31 UTC
Labels: bug
