### ISSUE TITLE
[BUG] fading no longer working for Bag and system bars since 10.0.5 release

### ISSUE THREAD

**Issue by mattenos** [PhenomDevel/BlizzHUDTweaks#46] opened 2023-01-30 17:26 UTC
## Description
Ability to fade the bag bar and system settings bar is no longer working since wow release 10.0.5

## Reproduce
Adjust settings for the bag and system bars to fade in any condition

## Expected Behaviour
Bag bar and system settings bar will fade according to the settings in the addon options

**Comment by PhenomDevel** [comment] 2023-01-30 17:36
Duplicate of #44 and should be fixed in the newest version from a few minutes ago :)

**Closed** 2023-02-01 16:49 UTC
Labels: bug
